openapi: 3.0.0
info:
  title: STD23057 - TD1
  version: 1.0.0

servers:
  - url: https://localhost.STD23057.com

paths:
  /customers:
    get:
      summary: Get a list of customers
      responses:
        '200':
          description: A list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'

components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        yearsOld:
          type: integer
